import Head from "next/head";
import Image from "next/image";
import HomeProducts from "../components/HomeProducts";
import Sidebar from "../components/Sidebar";
import { GraphQLClient, gql } from "graphql-request";
import Header from "../components/Header";
import Topmenu from "../components/Topmenu";
import CategoryMenu from "../components/CategoryMenu";
import Slider from "../components/Slider";
import PaginationSlider from "../components/PaginationSlider";
import AsideHome from "../components/AsideHome";
import PaginationArrorR from "../components/PaginationArrorR";
import PaginationArrowL from "../components/PaginationArrowL";

const graphcms = new GraphQLClient(
  "https://api-ap-southeast-2.hygraph.com/v2/clavgu89u2wfb01t4dyh4grkz/master"
);

const QUERY = gql`
  {
    sliders {
      sliderImage {
        url
      }
    }
    categories {
      categoryTitle
    }
    products {
      productPhoto1 {
        url
      }
      productPhoto2 {
        url
      }
      category {
        categoryTitle
      }
      tag {
        title
      }
      productTitle
      productDescription
      homeDescription
      productSlug
      stock
      deliveryDate
      deliveryArea
      fungsiDanPengukuran {
        html
      }
      productType
      productSize
      productDetail
    }
  }
`;

export async function getStaticProps() {
  const { categories, products, sliders } = await graphcms.request(QUERY);
  return {
    props: {
      categories,
      products,
      sliders,
    },
    revalidate: 10,
  };
}

export default function Home({ products, categories, sliders }) {
  return (
    <div>
      <Head>
        <title>Cikande Indobaja Mandiri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Topmenu />
      <Header />

      <div className="bg-[#8b8b8b] shadow-2xl flex flex-row justify-center gap-10 sticky top-0 z-20">
        {categories.map((category) => (
          <CategoryMenu categoryTitle={category.categoryTitle} />
        ))}
      </div>

      <div className="mx-auto flex flex-col h-[80vh] overflow-hidden">
        <div className="flex justify-between items-center mt-14">
          <PaginationArrowL />
          <div>
            {sliders.map((slider) => (
              <Slider sliderImage={slider.sliderImage} />
            ))}
          </div>
          <PaginationArrorR />
        </div>
        <PaginationSlider />
      </div>

      <div className="flex flex-row justify-center mt-10 gap-20 bg-white">
        <AsideHome />
        <div className="flex flex-wrap gap-10 w-[1200px] p-8">
          {products.map((product) => (
            <HomeProducts
              productTitle={product.productTitle}
              homeDescription={product.homeDescription}
              productSlug={product.productSlug}
              productPhoto1={product.productPhoto1}
            />
          ))}
        </div>
      </div>
    </div>
  );
}
